-- Kitne Ka? price list: 140 things Indian couples will recognise, prices in rupees, each checked against
-- the source listed (official site, retailer listing or news report) in the month given. Add more with more inserts;
-- never change a price in place without updating as_of.
insert into public.price_items (name, detail, category, emoji, price, source, as_of) values
  ('Amul Butter', '100 g pack', 'groceries', '🧈', 63, 'https://pricehistory.app/p/amul-salted-butter-pasteurised-100-grams-O2oClhce', '2026-10'),
  ('Aashirvaad Shudh Chakki Atta', '5 kg pack', 'groceries', '🌾', 267, 'https://pricehistory.app/p/aashirvaad-shudh-chakki-atta-5kg-pack-0PuAlaw8', '2026-10'),
  ('Brooke Bond Red Label Tea', '250 g pack', 'groceries', '🍵', 145, 'https://pricehistory.app/p/red-label-tea-250g-yVzassce', '2026-10'),
  ('Amul Pure Ghee', '1 litre tin', 'groceries', '🫕', 670, 'https://pricehistory.app/p/amul-ghee-pure-1-litre-tin-gojYnhce', '2026-07'),
  ('Tata Sampann Toor Dal', '500 g pack', 'groceries', '🫘', 113, 'https://pricehistory.app/p/tata-sampann-toor-dal-500g-GK6ZW6G5', '2026-10'),
  ('Maggi 2-Minute Masala Noodles', '420 g pouch (6 x 70 g)', 'groceries', '🍜', 83, 'https://pricehistory.app/p/maggi-2-minute-noodles-masala-420-grams-1RrNvoSj', '2026-10'),
  ('Tata Tea Premium Dumdaar Chai', '500 g pack', 'groceries', '☕', 280, 'https://pricehistory.app/p/tata-tea-premium-dumdaar-chai-500g-5fxjgfmb', '2026-10'),
  ('Taj Mahal Tea', '250 g pack', 'groceries', '🫖', 200, 'https://pricehistory.app/p/taj-mahal-tea-250g-flavour-orange-7Ik3taw8', '2026-10'),
  ('Rameshwaram Cafe Ghee Podi Idli', '1 plate (ghee podi idli) at The Rameshwaram Cafe, Bangalore', 'street-food', '🍛', 80, 'https://biryanimenu.com/rameshwaram-cafe-price-menu-list-in-bangalore/', '2025-09'),
  ('Rameshwaram Cafe Filter Coffee', '1 cup at The Rameshwaram Cafe, Bangalore', 'street-food', '☕', 25, 'https://biryanimenu.com/rameshwaram-cafe-price-menu-list-in-bangalore/', '2025-09'),
  ('McAloo Tikki Burger', '1 burger at McDonald''s, West & South India (McDelivery)', 'eating-out', '🍔', 79, 'https://www.grabon.in/indulge/food/mcdonalds-menu-prices-offers/', '2026-07'),
  ('Veg Maharaja Mac', '1 burger at McDonald''s India (McDelivery)', 'eating-out', '🍔', 235, 'https://www.grabon.in/indulge/food/mcdonalds-menu-prices-offers/', '2026-07'),
  ('McSpicy Paneer Burger', '1 burger at McDonald''s India (McDelivery)', 'eating-out', '🌶️', 225, 'https://www.grabon.in/indulge/food/mcdonalds-menu-prices-offers/', '2026-07'),
  ('McDonald''s Regular Fries', '1 regular fries at McDonald''s India', 'eating-out', '🍟', 85, 'https://www.grabon.in/indulge/food/mcdonalds-menu-prices-offers/', '2026-07'),
  ('Oreo McFlurry', '1 small cup at McDonald''s India', 'eating-out', '🍦', 109, 'https://www.grabon.in/indulge/food/mcdonalds-menu-prices-offers/', '2026-07'),
  ('Domino''s Margherita', '1 Regular pizza, Domino''s India (indicative, varies by city)', 'eating-out', '🍕', 109, 'https://www.grabon.in/indulge/food/dominos-pizza-menu-order-details/', '2026-07'),
  ('Domino''s Peppy Paneer', '1 Regular pizza, Domino''s India (indicative, varies by city)', 'eating-out', '🍕', 269, 'https://www.grabon.in/indulge/food/dominos-pizza-menu-order-details/', '2026-07'),
  ('Wow Momo Veg Momo Mania', '1 plate steamed veg momos at Wow! Momo (varies by outlet)', 'eating-out', '🥟', 69, 'https://www.paisawapas.com/blog/wow-momo-menu-with-prices/', '2026-08'),
  ('Wow Momo Veg Delight Momo', '1 plate steamed veg momos at Wow! Momo (varies by outlet)', 'eating-out', '🥟', 99, 'https://www.paisawapas.com/blog/wow-momo-menu-with-prices/', '2026-08'),
  ('Chaayos Desi Chai', '1 Desi Chai at Chaayos, Greater Kailash 2 Delhi outlet (Chaayos Bangalore may differ)', 'eating-out', '🫖', 111, 'https://magicpin.in/New-Delhi/Barakhamba-Road/Restaurant/Chaayos-Chai+Snacks=Relax/store/1b497/menu/', '2026-09'),
  ('Blue Tokai Cappuccino', '1 cappuccino at Blue Tokai Coffee Roasters, Bangalore', 'eating-out', '☕', 240, 'https://www.explorebangalore.com/cafes/blue-tokai-coffee-roasters/menu', '2026-01'),
  ('Starbucks Grande Caffe Latte', '1 Grande (473 ml) Caffe Latte at Starbucks India', 'eating-out', '☕', 340, 'https://pricemymeal.com/starbucks/india/', '2026-08'),
  ('Barbeque Nation Veg Lunch Buffet', 'Per head, Monday veg lunch buffet, Barbeque Nation India (weekends up to Rs 1049)', 'eating-out', '🍢', 799, 'https://www.paisawapas.com/blog/barbeque-nation-buffet/', '2026-01'),
  ('Netflix Mobile', 'per month, Mobile plan (1 phone/tablet, SD), India', 'subscriptions', '🎬', 149, 'https://help.netflix.com/en/node/24926', '2026-09'),
  ('Netflix Premium', 'per month, Premium plan (4K, 4 screens), India', 'subscriptions', '📺', 649, 'https://help.netflix.com/en/node/24926', '2026-09'),
  ('Spotify Premium Individual', 'per month, Premium Standard (individual) plan, India', 'subscriptions', '🎧', 139, 'https://www.spotify.com/in-en/premium/', '2026-10'),
  ('JioHotstar Super (Monthly)', 'per month, Super plan (Full HD, 2 devices, ads)', 'subscriptions', '📱', 149, 'https://telecomtalk.info/jiohotstar-subscription-plans-2026-mobile-super-premium/1004394/', '2026-01'),
  ('JioHotstar Premium (Annual)', 'per year, Premium plan (4K, 4 devices, mostly ad-free)', 'subscriptions', '🏏', 2199, 'https://telecomtalk.info/jiohotstar-subscription-plans-2026-mobile-super-premium/1004394/', '2026-01'),
  ('Amazon Prime (Annual)', 'per year, full Prime membership, India', 'subscriptions', '📦', 1499, 'https://www.aboutamazon.in/news/retail/new-amazon-prime-membership-plans-in-india', '2026-08'),
  ('Amazon Prime (Monthly)', 'per month, full Prime membership, India', 'subscriptions', '🛒', 299, 'https://zoutons.com/news/amazon-prime-price-plans-india-2026', '2026-08'),
  ('YouTube Premium Individual', 'per month, Individual plan, India', 'subscriptions', '▶️', 149, 'https://www.filmibeat.com/youtube-subscription-price-plans-45', '2026-09'),
  ('Apple Music Individual', 'per month, Individual plan, India (after July 2026 hike)', 'subscriptions', '🎵', 139, 'https://indiantelevision.com/iworld/apple-raises-apple-music-subscription-prices-across-india/', '2026-07'),
  ('iCloud+ 50GB', 'per month, 50GB plan, India (taxes included)', 'subscriptions', '☁️', 75, 'https://support.apple.com/en-in/108047', '2026-10'),
  ('ChatGPT Plus', 'per month, Plus plan, India (GST included)', 'subscriptions', '🤖', 1999, 'https://www.equityresearchindia.com/post/chatgpt-plus-and-pro-pricing-in-india-2026-complete-guide-in-rupees', '2026-08'),
  ('Zomato Gold (Annual)', 'per year, Zomato Gold annual plan, flat across cities', 'subscriptions', '🥇', 999, 'https://www.grabon.in/indulge/food/zomato-gold-membership-plan/', '2026-09'),
  ('iPhone 17', '256 GB, current Apple India price', 'gadgets', '📱', 99900, 'https://www.apple.com/in/shop/buy-iphone/iphone-17', '2026-10'),
  ('iPhone 17 Pro Max', '2 TB, Indian launch price (Sep 2025)', 'gadgets', '📱', 229900, 'https://www.croma.com/unboxed/iphone-17-iphone-17-pro-prices-in-india', '2025-09'),
  ('MacBook Air 13-inch M5', '16 GB RAM, 512 GB SSD, Indian launch price (Mar 2026)', 'gadgets', '💻', 119900, 'https://www.digit.in/news/laptops/apple-m5-macbook-air-launched-in-india-heres-whats-new-and-india-prices.html', '2026-03'),
  ('MacBook Pro 14-inch M5', '16 GB RAM, 512 GB SSD, Indian launch price (Oct 2025)', 'gadgets', '💻', 169900, 'https://www.business-standard.com/technology/gadgets/apple-macbook-pro-14-inch-m5-chip-launch-price-india-specifications-125101600618_1.html', '2025-10'),
  ('Apple AirPods Pro 3', 'current Apple India price', 'gadgets', '🎧', 27900, 'https://www.apple.com/in/shop/buy-airpods/airpods-pro-3', '2026-10'),
  ('Apple Watch SE 3', 'starting price, 40 mm GPS, Apple India', 'gadgets', '⌚', 29900, 'https://www.apple.com/in/shop/buy-watch/apple-watch', '2026-10'),
  ('Apple Watch Ultra 4', '49 mm, starting price, Apple India', 'gadgets', '⌚', 109900, 'https://www.apple.com/in/shop/buy-watch/apple-watch', '2026-10'),
  ('Samsung Galaxy S25', '12 GB + 256 GB, Indian launch price (Jan 2025)', 'gadgets', '📱', 80999, 'https://www.fonearena.com/blog/444701/samsung-galaxy-s25-s25-plus-s25-ultra-india-price.html', '2025-01'),
  ('Samsung Galaxy S25 Ultra', '12 GB + 256 GB, Indian launch price (Jan 2025)', 'gadgets', '📱', 129999, 'https://www.fonearena.com/blog/444701/samsung-galaxy-s25-s25-plus-s25-ultra-india-price.html', '2025-01'),
  ('Samsung Galaxy Buds 3 Pro', 'Indian launch price (Jul 2024)', 'gadgets', '🎧', 19999, 'https://www.sammobile.com/news/galaxy-buds-buds-3-pro-pricing-revealed-for-india/', '2024-07'),
  ('OnePlus 13', '12 GB + 256 GB, Indian launch price (Jan 2025)', 'gadgets', '📱', 69999, 'https://www.phonebunch.com/news/oneplus-13-launch-india-price-specifications_8133.html', '2025-01'),
  ('OnePlus Nord Buds 3 Pro', 'Indian launch price (Jul 2024)', 'gadgets', '🎧', 3299, 'https://www.mobigyaan.com/oneplus-nord-buds-3-pro-india', '2024-07'),
  ('OnePlus Nord Buds 3', 'Indian launch price (Sep 2024)', 'gadgets', '🎧', 2299, 'https://www.business-standard.com/technology/gadgets/oneplus-nord-buds-3-launches-in-india-with-anc-and-improved-bass-details-124091700398_1.html', '2024-09'),
  ('Nothing Phone (3a)', '8 GB + 128 GB, Indian launch price', 'gadgets', '📱', 24999, 'https://www.91mobiles.com/nothing-phone-3a-price-in-india', '2025-03'),
  ('Sony WH-1000XM5', 'MRP on Sony India store', 'gadgets', '🎧', 34990, 'https://www.sony.co.in/electronics/headband-headphones/wh-1000xm5/buy/wh1000xm5-bmin', '2026-10'),
  ('Google Pixel 10', '12 GB + 256 GB, Indian launch price (Aug 2025)', 'gadgets', '📱', 79999, 'https://www.cashify.in/google-pixel-10-price-in-india', '2025-08'),
  ('Redmi Note 14 5G', '6 GB + 128 GB, Indian launch price (Dec 2024)', 'gadgets', '📱', 17999, 'https://www.91mobiles.com/xiaomi-redmi-note-14-price-in-india', '2024-12'),
  ('Amazon Fire TV Stick 4K', 'MRP', 'gadgets', '📺', 6499, 'https://www.aish4aish.in/compare/fire-tv-stick-price-india', '2026-07'),
  ('Logitech M331 Silent Plus', 'wireless mouse, MRP', 'gadgets', '🖱️', 1645, 'https://www.amazon.in/Logitech-Silent-Wireless-Mouse-Black/dp/B01MQ2A86A', '2026-10'),
  ('Kindle Paperwhite (12th Gen)', '16 GB, Wi-Fi, Indian launch price (Apr 2025)', 'gadgets', '📖', 16999, 'https://www.fonearena.com/blog/452628/amazon-kindle-paperwhite-12th-gen-price-india-features.html', '2025-04'),
  ('IKEA BILLY Bookcase', 'white, 40x28x106 cm', 'home', '📚', 2990, 'https://www.ikea.com/in/en/cat/bookcases-st002/', '2026-10'),
  ('IKEA KALLAX Shelving Unit', 'white, 147x147 cm', 'home', '🗄️', 14990, 'https://www.ikea.com/in/en/cat/bookcases-st002/', '2026-10'),
  ('IKEA HYLLIS Shelving Unit', 'in/outdoor, 60x27x74 cm', 'home', '🧰', 1190, 'https://www.ikea.com/in/en/cat/bookcases-st002/', '2026-10'),
  ('IKEA MICKE Desk', 'white, 142x50 cm', 'home', '🖥️', 8990, 'https://www.ikea.com/in/en/cat/desks-computer-desks-20649/', '2026-10'),
  ('IKEA MALM Ottoman Bed', 'white, 180x200 cm', 'home', '🛏️', 50990, 'https://www.ikea.com/in/en/cat/mattresses-bm003/', '2026-10'),
  ('IKEA BAGGEBO Glass-door Cabinet', '34x30x116 cm', 'home', '🗄️', 3990, 'https://www.ikea.com/in/en/cat/storage-boxes-baskets-st003/', '2026-10'),
  ('IKEA POANG Armchair', 'basic model, black-brown frame', 'home', '🪑', 9990, 'https://www.ikea.com/in/en/cat/armchairs-fu006/', '2026-10'),
  ('IKEA SANDSBERG Chair', 'single dining chair', 'home', '🪑', 850, 'https://www.ikea.com/in/en/cat/chairs-fu002/', '2026-10'),
  ('Ray-Ban Wayfarer sunglasses', 'RB2140, black/G-15 green, 50 mm', 'fashion', '🕶️', 12790, 'https://india.ray-ban.com/0rb2140-green-901.html', '2026-10'),
  ('Casio F-91W watch', 'F-91W-1DG digital, MRP', 'fashion', '⌚', 1292, 'https://www.flipkart.com/casio-f-91w-1dg-youth-f-91w-1q-digital-watch-men/p/itm0dbd35985f508', '2026-10'),
  ('Uniqlo AIRism Cotton T-Shirt', 'men''s crew neck, short sleeve', 'fashion', '👕', 990, 'https://www.uniqlo.com/in/en/men/airism', '2026-10'),
  ('Titan Edge Baseline watch', 'blue dial, MRP', 'fashion', '⌚', 16995, 'https://www.flipkart.com/q/titan-edge-watches', '2026-10'),
  ('Fastrack Stunners watch', 'blue dial, silver metal strap, MRP', 'fashion', '⌚', 1495, 'https://www.flipkart.com/q/fastrack-watches', '2026-10'),
  ('Skybags Stroke Neo cabin trolley', '22 inch, printed, MRP', 'fashion', '🧳', 4700, 'https://www.flipkart.com/q/skybags-trolley', '2026-10'),
  ('Woodland lace-up casual shoes', 'camel, men''s, MRP', 'fashion', '🥾', 4495, 'https://www.flipkart.com/q/woodland-shoes', '2026-10'),
  ('Puma Softride Carson running shoes', 'men''s, MRP', 'fashion', '👟', 5999, 'https://www.flipkart.com/q/puma-softride-shoes', '2026-10'),
  ('Adidas Samba OG sneakers', 'men''s, MRP', 'fashion', '👟', 11999, 'https://www.flipkart.com/q/adidas-samba', '2026-10'),
  ('Allen Solly casual shirt', 'men''s regular fit, solid white, MRP', 'fashion', '👔', 1749, 'https://www.flipkart.com/q/allen-solly-shirt', '2026-10'),
  ('Wildcraft Zeal backpack', '17 L, MRP', 'fashion', '🎒', 1799, 'https://www.flipkart.com/q/wildcraft-backpack', '2026-10'),
  ('Crocs Classic Clog', 'men''s, MRP (Amazon lists about Rs 4,495)', 'fashion', '🩴', 3995, 'https://www.flipkart.com/crocs-classic-men-clogs/p/itm7bcb6630e774f', '2026-10'),
  ('Quechua hiking backpack', 'Decathlon 20 L, MRP (sells at Rs 599)', 'fashion', '🎒', 999, 'https://www.decathlon.in/c/hiking-backpacks-26142', '2026-10'),
  ('Jockey men''s vest', 'pack of 2, style 8820, MRP', 'fashion', '🎽', 499, 'https://www.flipkart.com/q/jockey-vest', '2026-10'),
  ('Lakme 9 to 5 Eyeconic Liquid Eyeliner', '4.5 ml, MRP', 'beauty', '👁️', 325, 'https://www.purplle.com/brand/lakme', '2026-10'),
  ('Mamaearth Onion Shampoo', '250 ml, MRP', 'beauty', '🧴', 349, 'https://www.purplle.com/brand/mamaearth', '2026-10'),
  ('Mamaearth Ubtan Face Wash', '100 ml, MRP', 'beauty', '🧼', 285, 'https://www.purplle.com/brand/mamaearth', '2026-10'),
  ('Himalaya Neem Face Wash', 'Purifying, 150 ml, selling price (MRP not shown)', 'beauty', '🌿', 279, 'https://www.purplle.com/brand/himalaya', '2026-10'),
  ('Nivea Soft Light Moisturiser', 'Berry Blossom, 100 ml, MRP', 'beauty', '🧴', 290, 'https://www.purplle.com/brand/nivea', '2026-10'),
  ('Vaseline Cocoa Glow Body Lotion', 'Serum in Lotion, 400 ml, MRP', 'beauty', '🧴', 640, 'https://www.purplle.com/brand/vaseline', '2026-10'),
  ('Pond''s Super Light Gel', '100 ml, MRP', 'beauty', '💧', 415, 'https://www.purplle.com/brand/ponds', '2026-10'),
  ('Dove Hair Fall Rescue Shampoo', '340 ml, MRP', 'beauty', '🚿', 435, 'https://www.purplle.com/brand/dove', '2026-10'),
  ('Maybelline Colossal Bold Pencil Eyeliner', '3 ml, black, waterproof, MRP', 'beauty', '✏️', 319, 'https://www.purplle.com/brand/maybelline', '2026-10'),
  ('Sugar Kohl of Honour Kajal', '0.3 g, Black Out, MRP', 'beauty', '👁️', 249, 'https://www.purplle.com/brand/sugar', '2026-10'),
  ('Wild Stone Edge perfume', 'men''s, 50 ml, MRP', 'beauty', '🌸', 499, 'https://www.purplle.com/brand/wild-stone', '2026-10'),
  ('Biotique Papaya Face Wash', 'Deep Cleanse, 100 ml, MRP', 'beauty', '🥭', 199, 'https://www.purplle.com/brand/biotique', '2026-10'),
  ('Rolls-Royce Cullinan', 'ex-showroom India, base', 'luxury', '🚙', 65700000, 'https://www.carwale.com/rolls-royce-cars/cullinan/', '2026-10'),
  ('Lamborghini Revuelto', 'ex-showroom India', 'luxury', '🏎️', 87000000, 'https://www.carwale.com/lamborghini-cars/revuelto/', '2026-10'),
  ('Ferrari Roma', 'ex-showroom India', 'luxury', '🏎️', 35600000, 'https://www.carwale.com/ferrari-cars/roma/', '2026-10'),
  ('Mercedes-Maybach S-Class', 'ex-showroom India, launched Oct 2026', 'luxury', '🚘', 32000000, 'https://www.carwale.com/mercedes-benz-cars/maybach-s-class/', '2026-10'),
  ('Mercedes-Benz S-Class', 'S 450e Launch Edition, ex-showroom India', 'luxury', '🚘', 22000000, 'https://www.carwale.com/mercedes-benz-cars/s-class/', '2026-10'),
  ('Porsche 911 Carrera', 'ex-showroom India, base', 'luxury', '🏎️', 21100000, 'https://www.carwale.com/porsche-cars/911/', '2026-10'),
  ('BMW 7 Series', '740i M Sport, ex-showroom India', 'luxury', '🚗', 19500000, 'https://www.carwale.com/bmw-cars/7-series/', '2026-10'),
  ('Audi Q7', 'base, ex-showroom India', 'luxury', '🚙', 8762000, 'https://www.carwale.com/audi-cars/q7/', '2026-10'),
  ('Rolex Submariner Date', 'Oystersteel, ref 126610LN, India 2026 list price', 'luxury', '⌚', 1051000, 'https://luxe.outlookindia.com/watches-jewellery/watches/new-rolex-prices-for-2026-full-list-of-models-and-costs', '2026-10'),
  ('Omega Speedmaster Moonwatch', '42 mm steel, 310.30.42.50.01.002, authorised retailer', 'luxury', '🌙', 929300, 'https://www.kapoorwatch.com/watches/omega/speedmaster', '2026-10'),
  ('Maruti Alto K10', 'ex-showroom Delhi, STD (O) base variant', 'vehicles', '🚗', 407000, 'https://www.carwale.com/maruti-suzuki-cars/alto-k10/', '2026-10'),
  ('Tata Punch', 'ex-showroom, Smart base variant', 'vehicles', '🚙', 575000, 'https://www.carwale.com/tata-cars/punch/', '2026-10'),
  ('Maruti Swift', 'ex-showroom, base variant', 'vehicles', '🚗', 584000, 'https://www.carwale.com/maruti-suzuki-cars/swift/', '2026-10'),
  ('Tata Nexon', 'ex-showroom Delhi, Smart base variant', 'vehicles', '🚙', 740000, 'https://www.carwale.com/tata-cars/nexon/', '2026-10'),
  ('Mahindra Thar', 'ex-showroom Delhi, AXT base variant', 'vehicles', '🛻', 1032000, 'https://www.carwale.com/mahindra-cars/thar/', '2026-10'),
  ('Hyundai Creta', 'ex-showroom Delhi, E base variant', 'vehicles', '🚙', 1091000, 'https://www.carwale.com/hyundai-cars/creta/', '2026-10'),
  ('Mahindra Scorpio-N', 'ex-showroom, Z2 base variant', 'vehicles', '🚙', 1369000, 'https://www.carwale.com/mahindra-cars/scorpio-n/', '2026-10'),
  ('Toyota Innova Crysta', 'ex-showroom Delhi, GX base variant', 'vehicles', '🚐', 1972000, 'https://www.carwale.com/toyota-cars/innova-crysta/', '2026-10'),
  ('Toyota Fortuner', 'ex-showroom Delhi, 4x2 base variant', 'vehicles', '🚙', 3476000, 'https://www.carwale.com/toyota-cars/fortuner/', '2026-10'),
  ('BYD Seal', 'ex-showroom, Dynamic base variant', 'vehicles', '⚡', 4150000, 'https://www.carwale.com/byd-cars/seal/', '2026-10'),
  ('Honda Activa 6G', 'ex-showroom, Standard base variant', 'vehicles', '🛵', 78964, 'https://www.bikewale.com/honda-bikes/activa-6g/', '2026-10'),
  ('TVS Jupiter', 'ex-showroom, base variant', 'vehicles', '🛵', 77373, 'https://www.bikewale.com/tvs-bikes/jupiter/', '2026-10'),
  ('Hero Splendor Plus', 'ex-showroom, base variant', 'vehicles', '🏍️', 77751, 'https://www.bikewale.com/hero-bikes/splendor-plus/', '2026-10'),
  ('Royal Enfield Hunter 350', 'ex-showroom, base variant', 'vehicles', '🏍️', 137640, 'https://www.bikewale.com/royalenfield-bikes/hunter-350/', '2026-10'),
  ('Royal Enfield Classic 350', 'ex-showroom, Redditch base variant', 'vehicles', '🏍️', 188934, 'https://www.bikewale.com/royalenfield-bikes/classic-350/', '2026-10'),
  ('Ather 450X', 'ex-showroom, base variant (2.9 kWh)', 'vehicles', '🛴', 150498, 'https://www.bikewale.com/ather-bikes/450x/', '2026-10'),
  ('Bajaj Chetak', 'ex-showroom, 3001 base variant', 'vehicles', '🛴', 119058, 'https://www.bikewale.com/bajaj-bikes/chetak/', '2026-10'),
  ('Yamaha R15 V4', 'ex-showroom, Standard variant', 'vehicles', '🏍️', 175693, 'https://www.bikewale.com/yamaha-bikes/yzf-r15/', '2026-10'),
  ('KTM 200 Duke', 'ex-showroom, base', 'vehicles', '🏍️', 191570, 'https://www.bikewale.com/ktm-bikes/200-duke/', '2026-10'),
  ('Namma Metro Majestic to Whitefield', 'Purple Line, token fare, one way', 'travel', '🚇', 80, 'https://www.bengalurumetrolines.in/route/majestic-to-whitefield', '2026-09'),
  ('Petrol per litre Bangalore', 'retail price on 9 Oct 2026', 'travel', '⛽', 111, 'https://www.goodreturns.in/petrol-price-in-bangalore.html', '2026-10'),
  ('Diesel per litre Bangalore', 'retail price on 9 Oct 2026', 'travel', '⛽', 99, 'https://www.goodreturns.in/diesel-price-in-bangalore.html', '2026-10'),
  ('CNG per kg Delhi', 'retail price on 9 Oct 2026', 'travel', '⛽', 87, 'https://www.goodreturns.in/cng-price-in-delhi.html', '2026-10'),
  ('FASTag Annual Pass', 'NHAI, FY 2026-27 (valid 1 year or 200 trips)', 'travel', '🛣️', 3075, 'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2240305&lang=1&reg=3', '2026-04'),
  ('Indian passport fee', 'fresh 36-page, adult, normal, from 1 Jul 2026', 'travel', '🛂', 2500, 'https://www.zurichkotak.com/knowledge-center/travel-insurance/passport-fees-in-india', '2026-07'),
  ('Delhi Airport Express metro', 'New Delhi to IGI Airport T3, one way', 'travel', '🚇', 60, 'https://en.wikipedia.org/wiki/Airport_Express_(Delhi_Metro)', '2026-10'),
  ('Mysore Palace entry', 'adult Indian visitor, per person', 'experiences', '🏰', 120, 'https://en.wikipedia.org/wiki/Mysore_Palace', '2025-12'),
  ('Gold 24k (10 g)', '24 karat, 10 grams, Bangalore, excl. GST, on 9 Oct 2026', 'luxury', '🥇', 150710, 'https://www.goodreturns.in/gold-rates/bangalore.html', '2026-10'),
  ('Gold 22k (10 g)', '22 karat, 10 grams, Delhi, excl. GST, on 9 Oct 2026', 'luxury', '💍', 138300, 'https://www.goodreturns.in/gold-rates/delhi.html', '2026-10'),
  ('Silver (1 kg)', '1 kg silver, Bangalore, on 9 Oct 2026', 'weird', '🥈', 234900, 'https://www.goodreturns.in/silver-rates/bangalore.html', '2026-10'),
  ('LPG cylinder', '14.2 kg domestic, Bangalore', 'home', '🔥', 945, 'https://www.goodreturns.in/lpg-price-in-bangalore.html', '2026-10'),
  ('Tatkal passport', '36 pages, adult, total fee under Tatkal, from 1 Jul 2026', 'weird', '📘', 5000, 'https://www.zurichkotak.com/knowledge-center/travel-insurance/passport-fees-in-india', '2026-07'),
  ('UPSC Civil Services exam fee', 'General male candidates (women/SC/ST/PwBD exempt)', 'weird', '📝', 100, 'https://en.wikipedia.org/wiki/Civil_Services_Examination', '2026-10'),
  ('JEE Main application fee', 'General category, per 2025 bulletin', 'weird', '🎓', 1000, 'https://en.wikipedia.org/wiki/Joint_Entrance_Examination_%E2%80%93_Main', '2025-01'),
  ('CAT registration fee', 'General/EWS/NC-OBC', 'weird', '📚', 2600, 'https://en.wikipedia.org/wiki/Common_Admission_Test', '2025-08'),
  ('Inland letter by India Post', 'Ordinary letter up to 20 g', 'weird', '✉️', 5, 'https://www.indiapost.gov.in/mailproducts/domesticservices/domestictariff', '2026-10'),
  ('Kerala Onam Bumper ticket', 'Thiruvonam Bumper BR-111, Rs 30 crore first prize', 'weird', '🎟️', 500, 'https://www.hailakochi.com/articles/kochi-onam-bumper-lottery-2026-guide', '2026-09'),
  ('Tirupati laddu', 'Small Srivari laddu, about 175 g, at Tirumala', 'weird', '🟠', 50, 'https://tirumalatirupatiguide.in/ttd-laddu-price-2026/', '2026-10'),
  ('Nandini toned milk', '1 litre blue packet, Karnataka (hike pending)', 'groceries', '🥛', 46, 'https://www.karmactive.com/nandini-milk-price-hike-karnataka-8-rupees', '2026-10'),
  ('Parle-G', 'the smallest pack', 'snacks', '🍪', 5, null, '2026-10'),
  ('Bisleri water', '1 litre bottle, MRP', 'snacks', '💧', 20, null, '2026-10');
